services:
  postgres:
    image: postgres:15
    container_name: go_web_dev_template_db
    restart: always
    environment:
      POSTGRES_USER: gowebdev
      POSTGRES_PASSWORD: gowebdevsecret
      POSTGRES_DB: gowebdevdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_web_dev_template_backend
    restart: always
    environment:
      DATABASE_URL: postgres://gowebdev:gowebdevsecret@postgres:5432/gowebdevdb?sslmode=disable
      JWT_SECRET_KEY: jwtsecretkey
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
